import type { Metadata } from "next";
import { Inter as FontSans } from "next/font/google"
import { Inter } from "next/font/google";
import { Navbar } from "@/components/layouts/Navbar";
import "./globals.css";
import Footer from "@/components/layouts/Footer";
import SessionWrapper from "@/components/resources/actions/SessionWrapper";
import { SessionProvider } from "next-auth/react";

const inter = Inter({ subsets: ["latin"] });
const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
})
 

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <SessionProvider>
          <Navbar/>
        {children}
        <Footer/>
        </SessionProvider>
      
        </body>
    </html>
  );
}
